name: Notify Parent Repo

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  notify-parent:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Parent Repository Workflow
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.PAT }}" \
          -d '{"event_type": "update_submodules"}' \
          https://api.github.com/repos/P72024/P7Project/dispatches
